android_install {
    DEFAULT_ANDROID_SDK_ROOT = 
    DEFAULT_ANDROID_NDK_ROOT = 
    DEFAULT_ANDROID_PLATFORM = android-9
    DEFAULT_ANDROID_NDK_HOST = windows
    DEFAULT_ANDROID_TARGET_ARCH = armeabi-v7a
    DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION = 4.7
}
